# Generated by Django 4.2.6 on 2023-11-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=200)),
                ('reader_name', models.CharField(max_length=200)),
                ('reader_contact', models.CharField(max_length=200)),
                ('reader_address', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
