# Generated by Django 4.2.6 on 2023-11-21 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='isbn',
            new_name='ISBN',
        ),
    ]
