# Generated by Django 4.2.6 on 2023-11-30 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0002_book_mybag'),
        ('lims_app', '0002_books'),
    ]

    operations = [
    ]
