# Generated by Django 4.2.6 on 2023-11-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0003_merge_0002_book_mybag_0002_books'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.RemoveField(
            model_name='mybag',
            name='book_returndate',
        ),
        migrations.RemoveField(
            model_name='mybag',
            name='book_startdate',
        ),
        migrations.RemoveField(
            model_name='mybag',
            name='reader_contact',
        ),
        migrations.RemoveField(
            model_name='mybag',
            name='reader_name',
        ),
        migrations.AddField(
            model_name='books',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='book/'),
        ),
    ]
