# Generated by Django 4.2.6 on 2023-12-01 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lims_app', '0005_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybag',
            name='book_name',
        ),
        migrations.RemoveField(
            model_name='mybag',
            name='reference_id',
        ),
        migrations.AddField(
            model_name='mybag',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lims_app.books'),
        ),
        migrations.AddField(
            model_name='mybag',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
