# Generated by Django 4.2.6 on 2023-12-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0007_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='return_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
