# Generated by Django 4.2.6 on 2023-12-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims_app', '0008_alter_orders_order_date_alter_orders_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='return_status',
            field=models.CharField(choices=[('Returned', 'Returned'), ('Not Returned', 'Not Returned')], default='Not Returned', max_length=50),
        ),
    ]
